export const steps = [
  {
    step: 1,
    title: "Etape 1",
    subtitle: "Première courone",
    cubes: [
      {
        title: "Cas 1",
        top: ["", "", "", "", "", "", "", "", "g"],
        right: ["o", "", "", "", "o", "", "", "o", ""],
        left: ["", "", "w", "", "g", "", "", "g", ""],
        moves: [
          { face: "t", arrow: "l" },
          { face: "r", arrow: "t" },
          { face: "t", arrow: "r" },
          { face: "r", arrow: "b" },
        ],
      },
      {
        title: "Cas 2",
        top: ["", "", "", "", "", "", "", "", "o"],
        right: ["w", "", "", "", "o", "", "", "o", ""],
        left: ["", "", "g", "", "g", "", "", "g", ""],
        moves: [
          { face: "t", arrow: "r" },
          { face: "f", arrow: "rl" },
          { face: "t", arrow: "l" },
          { face: "f", arrow: "rr" },
        ],
      },
      {
        title: "Cas 3",
        badge: "x3",
        top: ["", "", "", "", "", "", "", "", "w"],
        right: ["g", "", "", "", "o", "", "", "o", ""],
        left: ["", "", "o", "", "g", "", "", "g", ""],
        moves: [
          { face: "r", arrow: "t" },
          { face: "t", arrow: "l" },
          { face: "r", arrow: "b" },
          { face: "t", arrow: "r" },
        ],
      },
    ],
  },
  {
    step: 2,
    title: "Etape 2",
    subtitle: "Deuxième courone",
    cubes: [
      {
        title: "Cas 1",
        top: ["", "", "", "", "", "", "", "o", ""],
        right: ["", "", "", "", "o", "", "o", "o", "o"],
        left: ["", "g", "", "", "g", "", "g", "g", "g"],
        moves: [
          { face: "t", arrow: "l" },
          { face: "r", arrow: "t" },
          { face: "t", arrow: "r" },
          { face: "r", arrow: "b" },
          { face: "f", arrow: "rr" },
          { face: "r", arrow: "b" },
          { face: "f", arrow: "rr" },
          { face: "r", arrow: "t" },
        ],
      },
      {
        title: "Cas 2",
        top: ["", "", "", "", "", "g", "", "", ""],
        right: ["", "o", "", "", "o", "", "o", "o", "o"],
        left: ["", "", "", "", "g", "", "g", "g", "g"],
        moves: [
          { face: "t", arrow: "r" },
          { face: "f", arrow: "rl" },
          { face: "t", arrow: "l" },
          { face: "f", arrow: "rr" },
          { face: "t", arrow: "l" },
          { face: "r", arrow: "t" },
          { face: "t", arrow: "r" },
          { face: "r", arrow: "b" },
        ],
      },
      {
        title: "Cas 3",
        top: ["", "", "", "", "", "", "", "", ""],
        right: ["", "", "", "g", "o", "", "o", "o", "o"],
        left: ["", "", "", "", "g", "o", "g", "g", "g"],
        movesMsg: "Refaire le 1er ou deuxième cas pour déplacer l'arrête",
      },
    ],
  },
  {
    step: 3,
    title: "Etape 3",
    subtitle: "Troisième courone",
    cubes: [
      {
        title: "Cas 1",
        top: ["", "y", "", "y", "y", "", "", "", ""],
        right: ["", "", "", "o", "o", "o", "o", "o", "o"],
        left: ["", "", "", "g", "g", "g", "g", "g", "g"],
        moves: [
          { face: "r", arrow: "b" },
          { face: "t", arrow: "r" },
          { face: "f", arrow: "rl" },
          { face: "t", arrow: "l" },
          { face: "f", arrow: "rr" },
          { face: "r", arrow: "t" },
        ],
      },
      {
        title: "Cas 2",
        top: ["", "", "", "y", "y", "y", "", "", ""],
        right: ["", "", "", "o", "o", "o", "o", "o", "o"],
        left: ["", "", "", "g", "g", "g", "g", "g", "g"],
        moves: [
          { face: "f", arrow: "rr" },
          { face: "r", arrow: "t" },
          { face: "t", arrow: "l" },
          { face: "r", arrow: "b" },
          { face: "t", arrow: "r" },
          { face: "f", arrow: "rl" },
        ],
      },
      {
        title: "Cas 3",
        top: ["", "", "", "", "y", "", "", "", ""],
        right: ["", "", "", "o", "o", "o", "o", "o", "o"],
        left: ["", "", "", "g", "g", "g", "g", "g", "g"],
        movesMsg: "Refaire le 1er ou deuxième cas pour obtenir un des deux cas",
      },
    ],
  },
  {
    step: 4,
    title: "Etape 4",
    subtitle: "Fin",
    cubes: [
      {
        title: "Etape A",
        top: ["", "y", "", "y", "y", "y", "", "y", "y"],
        right: ["o", "o", "", "o", "o", "o", "o", "o", "o"],
        left: ["", "g", "g", "g", "g", "g", "g", "g", "g"],

        // top="['', 'y', '', 'y', 'y', 'y', '', 'y', 'g'],
        // left="['', 'g', 'o', 'g', 'g', 'g', 'g', 'g', 'g'],
        // right="['y', 'o', '', 'o', 'o', 'o', 'o', 'o', 'o']

        // top: "['', 'y', '', 'y', 'y', 'y', '', 'y', 'o'],
        // left: "['', 'g', 'y', 'g', 'g', 'g', 'g', 'g', 'g'],
        // right: "['g', 'o', '', 'o', 'o', 'o', 'o', 'o', 'o']

        moves: [
          { face: "l", arrow: "t" },
          { face: "t", arrow: "l" },
          { face: "r", arrow: "t" },
          { face: "t", arrow: "r" },
          { face: "l", arrow: "b" },
          { face: "t", arrow: "l" },
          { face: "r", arrow: "b" },
        ],
      },
      {
        title: "Etape B",
        top: [],
        right: [],
        left: [],
        moves: [
          { face: "r", arrow: "b" },
          { face: "b", arrow: "l" },
          { face: "r", arrow: "t" },
          { face: "b", arrow: "r" },
        ],
      },
      {
        title: "Etape C",
        top: [],
        right: [],
        left: [],
        moves: [
          { face: "f", arrow: "rl" },
          { face: "t", arrow: "l" },
          { face: "t", arrow: "l" },
          { face: "f", arrow: "rr" },
          { face: "t", arrow: "l" },
          { face: "f", arrow: "rl" },
          { face: "t", arrow: "l" },
          { face: "f", arrow: "rr" },
          { face: "back", arrow: "rl" },
          { face: "t", arrow: "l" },
          { face: "t", arrow: "l" },
          { face: "back", arrow: "rr" },
          { face: "t", arrow: "l" },
          { face: "back", arrow: "rl" },
          { face: "t", arrow: "l" },
          { face: "back", arrow: "rr" },
        ],
      },
    ],
  },
  {
    step: 999,
    title: "Terminé !",
    subtitle: "Fin",
    cubes: [
      {
        top: ["y", "y", "y", "y", "y", "y", "y", "y", "y"],
        right: ["o", "o", "o", "o", "o", "o", "o", "o", "o"],
        left: ["g", "g", "g", "g", "g", "g", "g", "g", "g"],
      },
      {
        top: ["w", "w", "w", "w", "w", "w", "w", "w", "w"],
        left: ["o", "o", "o", "o", "o", "o", "o", "o", "o"],
        right: ["g", "g", "g", "g", "g", "g", "g", "g", "g"],
      },
    ],
  },
];
